apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    orgId: 1
    url: http://development-prometheus-1:9090
    isDefault: true
  - name: prometheus-ephem
    type: prometheus
    orgId: 1
    url: http://development-prometheus-ephem-1:9090
    isDefault: false
