apiVersion: v1
kind: Template
metadata:
  name: kafka-connector
objects:
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaConnector
  metadata:
    name: kessel-inventory-source-connector
    labels:
      strimzi.io/cluster: ${KAFKA_CONNECT_INSTANCE}
  spec:
    class: io.debezium.connector.postgresql.PostgresConnector
    tasksMax: ${{MAX_TASKS}}
    config:
      database.server.name: ${DB_SERVERNAME}
      database.dbname: ${DB_NAME}
      database.hostname: ${DB_HOSTNAME}
      database.port: ${DB_PORT}
      database.user: ${DB_USER}
      database.password: ${DB_PASSWORD}
      topic.prefix: kessel-inventory
      table.include.list: public.outbox_events
      transforms: outbox
      transforms.outbox.type: io.debezium.transforms.outbox.EventRouter
      plugin.name: pgoutput
      heartbeat.interval.ms: ${DEBEZIUM_HEARTBEAT_INTERVAL_MS}
      heartbeat.action.query: ${DEBEZIUM_ACTION_QUERY}
      topic.heartbeat.prefix: ${TOPIC_HEARTBEAT_PREFIX}
parameters:
- name: DB_SERVERNAME
  required: true
  description: Logical name that identifies and provides a namespace for the particular database server
  value: kessel-inventory-db
- name: DB_NAME
  required: true
  description: Name for the database
- name: DB_HOSTNAME
  required: true
  description: URI for the target postgres database
- name: DB_PORT
  value: "5432"
  description: Port on which the target postgres database is listening for connections
- name: DB_USER
  description: Username the connector should use to connect to the target postgres database
  required: true
- name: DB_PASSWORD
  description: Password for the above user on the target postgres database
  required: true
- name: KAFKA_CONNECT_INSTANCE
  value: platform-kafka-connect
  description: Name of the target Kafka Connect instance for Connector
- name: MAX_TASKS
  value: "1"
  description: How many tasks the Kafka Connect instance can create to process this Connector's work
- name: TOPIC_HEARTBEAT_PREFIX
  value: debezium-heartbeat
  description: Prefix for the connector heartbeat topic
- name: DEBEZIUM_ACTION_QUERY
  value: "SELECT pg_logical_emit_message(false, 'heartbeat', now()::varchar);"
  description: Query action that runs for each heartbeat event
- name: DEBEZIUM_HEARTBEAT_INTERVAL_MS
  value: "300000"
  description: The interval for the Debezium heartbeat in ms
